CREATE TABLE "FRSF_PRELIM_ASSIGN_SR" (
    "PROJECT_HASH" VARCHAR2(128) NOT NULL ENABLE
    , "JUDGE_HASH" VARCHAR2(128) NOT NULL ENABLE
    , "TIME" TIMESTAMP(6) DEFAULT systimestamp
    , CONSTRAINT "FRSF_PRELIM_ASSIGN_SR_PK" PRIMARY KEY ( "PROJECT_HASH", "JUDGE_HASH" ) USING INDEX enable
)
NO INMEMORY;