CREATE TABLE "FRSF_PRELIM_PROJECT_SR" (
      "PROJECT_HASH" VARCHAR2(128) NOT NULL ENABLE
    , "PROJECT_ID" VARCHAR2(26)
    , "TITLE" VARCHAR2(256)
    , "STUDENT_NAMES" VARCHAR2(128)
    , "JUDGE_COUNT" NUMBER
    , CONSTRAINT "FRSF_PRELIM_PROJECT_SR_PK" PRIMARY KEY ( "PROJECT_HASH" ) USING INDEX enable
)
NO INMEMORY;