CREATE TABLE "FRSF_FINAL_GROUP_COUNT_SR" (
   "GROUP_ID" NUMBER
      NOT NULL ENABLE
   , "PROJECT_COUNT" VARCHAR2(20) DEFAULT 0
   , CONSTRAINT "TABLE1_PK" PRIMARY KEY ( "GROUP_ID" )
      USING INDEX enable
)
NO INMEMORY;