CREATE TABLE "FRSF_FINAL_PROJECT_SR" (
   "PROJECT_HASH" VARCHAR2(128)
      NOT NULL ENABLE
   , "PROJECT_ID" VARCHAR2(26)
   , "TITLE" VARCHAR2(256)
   , "STUDENT_NAMES" VARCHAR2(128)
   , "GROUP_COUNT" NUMBER
)
NO INMEMORY;