CREATE TABLE "FRSF_PRELIM_JUDGE_SR" (
    "JUDGE_HASH" VARCHAR2(128) NOT NULL ENABLE
    , "FIRST_NAME" VARCHAR2(26)
    , "LAST_NAME" VARCHAR2(26)
    , "EMAIL" VARCHAR2(128)
    , "PROJECT_COUNT" NUMBER
    , CONSTRAINT "FRSF_PRELIM_JUDGE_SR_PK" PRIMARY KEY ( "JUDGE_HASH" ) USING INDEX enable
)
NO INMEMORY;