CREATE TABLE "ZFAIR_ASSIGN_PRELIMINARY" (
   "ZFAIR_ID" VARCHAR2(60)
   , "PROJECT_ID" VARCHAR2(60)
   , "JUDGE_ID" VARCHAR2(60)
   , "TIMESLOT" VARCHAR2(60)
   , PRIMARY KEY ( "ZFAIR_ID"
   , "JUDGE_ID" )
      USING INDEX enable
)
NO INMEMORY;

CREATE TABLE "ZFAIR_ASSIGN_FINALIST" (
   "ZFAIR_ID" VARCHAR2(60)
   , "PROJECT_ID" VARCHAR2(60)
   , "JUDGE_ID" VARCHAR2(60)
   , "TIMESLOT" VARCHAR2(60)
   , PRIMARY KEY ( "ZFAIR_ID"
   , "JUDGE_ID" )
      USING INDEX enable
)
NO INMEMORY;
;


CREATE TABLE "ZFAIR_ASSIGN_FINALIST_GROUPS" (
   "ZFAIR_ID" VARCHAR2(60)
   , "PROJECT_ID" VARCHAR2(60)
   , "GROUP_NAME" VARCHAR2(60)
   , "TIMESLOT" VARCHAR2(60)
   , PRIMARY KEY ( "ZFAIR_ID"
   , "GROUP_NAME" )
      USING INDEX enable
)
NO INMEMORY;