CREATE TABLE "ZFAIR_PROJECTS_PRELIMINARY" (
   "ZFAIR_ID" VARCHAR2(60)
   , "PROJECT_ID" VARCHAR2(60)
   , "TITLE" VARCHAR2(1024)
   , "STUDENT_NAMES" VARCHAR2(1024)
   , "JUDGE_COUNT" NUMBER(*, 0)
   , PRIMARY KEY ( "ZFAIR_ID" )
      USING INDEX enable
)
NO INMEMORY;

CREATE TABLE "ZFAIR_PROJECTS_FINALIST" (
   "ZFAIR_ID" VARCHAR2(60)
   , "PROJECT_ID" VARCHAR2(60)
   , "TITLE" VARCHAR2(1024)
   , "STUDENT_NAMES" VARCHAR2(1024)
   , "JUDGE_COUNT" NUMBER(*, 0)
   , PRIMARY KEY ( "ZFAIR_ID" )
      USING INDEX enable
)
NO INMEMORY;